resources:
- name: git
  type: git
  source:
    uri: git@github.com:kdvolder/concourse-tycho.git
    branch: master
    username: kdvolder
    private_key: {{rsa_id}}
- name: docker-git
  type: git
  source:
    uri: git@github.com:kdvolder/concourse-tycho.git
    branch: master
    username: kdvolder
    private_key: {{rsa_id}}
    paths:
    - concourse/docker
- name: docker-image
  type: docker-image
  source:
    username: {{docker_hub_username}}
    email: {{docker_hub_email}}
    password: {{docker_hub_password}}
    repository: kdvolder/tycho-test-env
jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: docker-git
    trigger: true
  - put: docker-image
    params:
      build: docker-git/concourse/docker
    get_params: 
      skip_download: true
- name: run-tests
  plan:
  - get: git
    trigger: true
  - get: docker-image
    trigger: true
    params:
      # The task pulls the image itself, so skip downloading here
      skip_download: true .
  - task: run-tests
    file: git/concourse/tasks/mvn-run.yml

