platform: linux

image_resource:
  type: docker-image
  source:
    repository: kdvolder/tycho-test-env

inputs:
- name: git

run:
  path: ./concourse/tasks/mvn-run.sh
  args: ["clean", "integration-test"]
  dir: git
